import uproot
import ROOT

def list_root_objects(file_path):
    try:
        with uproot.open(file_path) as file:
            print(f"Contents of ROOT file: {file_path}\n")
            
            for key in file.keys():
                print(f"{key}")
            
    except Exception as e:
        print(f"Error opening ROOT file: {e}")

if __name__ == "__main__":
    prino_path = "/home/giacomo/Downloads/PrimaryHits_pionsWithCNoTargNoB.root"
    list_root_objects(prino_path)
    prino_file = ROOT.TFile(prino_path, "READ")

    prino_res_x = prino_file.Get("hGausSigxVsLay")
    prino_res_y = prino_file.Get("hGausSigyVsLay")

    acts_path = "/home/giacomo/acts_for_NA60+/ACTS-Analysis-Scripts/analysis_scripts/hit_distributions.root"

    acts_file = ROOT.TFile(acts_path, "READ")
    

    acts_res_x = acts_file.Get("rms_x_converted")
    acts_res_y = acts_file.Get("rms_y_converted")

    fast_path = "/home/giacomo/na60fastsim_galocco/files/macros/kmc_analysis.root"
    fast_file = ROOT.TFile(fast_path,"read")

    prino_res_x.SetLineColor(ROOT.kRed)
    prino_res_y.SetLineColor(ROOT.kRed)
    acts_res_x.SetLineColor(ROOT.kBlue)
    acts_res_y.SetLineColor(ROOT.kBlue)
    prino_res_x.SetMarkerColor(ROOT.kRed)
    prino_res_y.SetMarkerColor(ROOT.kRed)
    acts_res_x.SetMarkerColor(ROOT.kBlue)
    acts_res_y.SetMarkerColor(ROOT.kBlue)
    prino_res_x.SetMarkerStyle(20)
    prino_res_y.SetMarkerStyle(20)
    acts_res_x.SetMarkerStyle(21)
    acts_res_y.SetMarkerStyle(21)

    cv = ROOT.TCanvas("cv", "Comparison of RMS", 800, 600)
    cv.Divide(2, 1)
    cv.cd(1)
    prino_res_x.Draw("E")
    acts_res_x.Draw("E SAME")
    cv.cd(2)
    prino_res_y.Draw("E")
    acts_res_y.Draw("E SAME")
    cv.Update()
    cv.SaveAs("comparison_rms.png")
    
    hxlay0prim = prino_file.Get("hxlay0prim")
    hylay0prim = prino_file.Get("hylay0prim")
    hxlay1prim = prino_file.Get("hxlay1prim")
    hylay1prim = prino_file.Get("hylay1prim")
    hxlay2prim = prino_file.Get("hxlay2prim")
    hylay2prim = prino_file.Get("hylay2prim")
    hxlay3prim = prino_file.Get("hxlay3prim")
    hylay3prim = prino_file.Get("hylay3prim")
    hxlay4prim = prino_file.Get("hxlay4prim")
    hylay4prim = prino_file.Get("hylay4prim")


    hx_layer0 = acts_file.Get("hx2_layer0")
    hy_layer0 = acts_file.Get("hy2_layer0")
    hx_layer1 = acts_file.Get("hx2_layer1")
    hy_layer1 = acts_file.Get("hy2_layer1")
    hx_layer2 = acts_file.Get("hx2_layer2")
    hy_layer2 = acts_file.Get("hy2_layer2")
    hx_layer3 = acts_file.Get("hx2_layer3")
    hy_layer3 = acts_file.Get("hy2_layer3")
    hx_layer4 = acts_file.Get("hx2_layer4")
    hy_layer4 = acts_file.Get("hy2_layer4")

    hx_layer0_fast = fast_file.Get("hist_x_z1")
    hy_layer0_fast = fast_file.Get("hist_y_z1")
    hx_layer1_fast = fast_file.Get("hist_x_z2")
    hy_layer1_fast = fast_file.Get("hist_y_z2")
    hx_layer2_fast = fast_file.Get("hist_x_z3")
    hy_layer2_fast = fast_file.Get("hist_y_z3")
    hx_layer3_fast = fast_file.Get("hist_x_z4")
    hy_layer3_fast = fast_file.Get("hist_y_z4")
    hx_layer4_fast = fast_file.Get("hist_x_z5")
    hy_layer4_fast = fast_file.Get("hist_y_z5")

    rebin = 2
    hxlay0prim.Rebin(rebin)
    hylay0prim.Rebin(rebin)
    hxlay1prim.Rebin(rebin)
    hylay1prim.Rebin(rebin)
    hxlay2prim.Rebin(rebin)
    hylay2prim.Rebin(rebin)
    hxlay3prim.Rebin(rebin)
    hylay3prim.Rebin(rebin)
    hxlay4prim.Rebin(rebin)
    hylay4prim.Rebin(rebin)


    hx_layer0.Rebin(rebin)
    hy_layer0.Rebin(rebin)
    hx_layer1.Rebin(rebin)
    hy_layer1.Rebin(rebin)
    hx_layer2.Rebin(rebin)
    hy_layer2.Rebin(rebin)
    hx_layer3.Rebin(rebin)
    hy_layer3.Rebin(rebin)
    hx_layer4.Rebin(rebin)
    hy_layer4.Rebin(rebin)


    hx_layer0_fast.Rebin(rebin)
    hy_layer0_fast.Rebin(rebin)
    hx_layer1_fast.Rebin(rebin)
    hy_layer1_fast.Rebin(rebin)
    hx_layer2_fast.Rebin(rebin)
    hy_layer2_fast.Rebin(rebin)
    hx_layer3_fast.Rebin(rebin)
    hy_layer3_fast.Rebin(rebin)
    hx_layer4_fast.Rebin(rebin)
    hy_layer4_fast.Rebin(rebin)


    hxlay0prim.GetListOfFunctions().Clear()
    hylay0prim.GetListOfFunctions().Clear()
    hxlay1prim.GetListOfFunctions().Clear()
    hylay1prim.GetListOfFunctions().Clear()
    hxlay2prim.GetListOfFunctions().Clear()
    hylay2prim.GetListOfFunctions().Clear()
    hxlay3prim.GetListOfFunctions().Clear()
    hylay3prim.GetListOfFunctions().Clear()
    hxlay4prim.GetListOfFunctions().Clear()
    hylay4prim.GetListOfFunctions().Clear()


    hx_layer0.SetLineColor(ROOT.kRed)
    hy_layer0.SetLineColor(ROOT.kRed)
    hx_layer1.SetLineColor(ROOT.kRed)
    hy_layer1.SetLineColor(ROOT.kRed)
    hx_layer2.SetLineColor(ROOT.kRed)
    hy_layer2.SetLineColor(ROOT.kRed)
    hx_layer3.SetLineColor(ROOT.kRed)
    hy_layer3.SetLineColor(ROOT.kRed)
    hx_layer4.SetLineColor(ROOT.kRed)
    hy_layer4.SetLineColor(ROOT.kRed)

    hx_layer0_fast.SetLineColor(ROOT.kBlue)
    hy_layer0_fast.SetLineColor(ROOT.kBlue)
    hx_layer1_fast.SetLineColor(ROOT.kBlue)
    hy_layer1_fast.SetLineColor(ROOT.kBlue)
    hx_layer2_fast.SetLineColor(ROOT.kBlue)
    hy_layer2_fast.SetLineColor(ROOT.kBlue)
    hx_layer3_fast.SetLineColor(ROOT.kBlue)
    hy_layer3_fast.SetLineColor(ROOT.kBlue)
    hx_layer4_fast.SetLineColor(ROOT.kBlue)
    hy_layer4_fast.SetLineColor(ROOT.kBlue)


    hx_layer0.Scale(1./hx_layer0.GetMaximum())
    hy_layer0.Scale(1./hy_layer0.GetMaximum())
    hx_layer1.Scale(1./hx_layer1.GetMaximum())
    hy_layer1.Scale(1./hy_layer1.GetMaximum())
    hx_layer2.Scale(1./hx_layer2.GetMaximum())
    hy_layer2.Scale(1./hy_layer2.GetMaximum())
    hx_layer3.Scale(1./hx_layer3.GetMaximum())
    hy_layer3.Scale(1./hy_layer3.GetMaximum())
    hx_layer4.Scale(1./hx_layer4.GetMaximum())
    hy_layer4.Scale(1./hy_layer4.GetMaximum())

    hx_layer0_fast.Scale(1./hx_layer0_fast.GetMaximum())
    hy_layer0_fast.Scale(1./hy_layer0_fast.GetMaximum())
    hx_layer1_fast.Scale(1./hx_layer1_fast.GetMaximum())
    hy_layer1_fast.Scale(1./hy_layer1_fast.GetMaximum())
    hx_layer2_fast.Scale(1./hx_layer2_fast.GetMaximum())
    hy_layer2_fast.Scale(1./hy_layer2_fast.GetMaximum())
    hx_layer3_fast.Scale(1./hx_layer3_fast.GetMaximum())
    hy_layer3_fast.Scale(1./hy_layer3_fast.GetMaximum())
    hx_layer4_fast.Scale(1./hx_layer4_fast.GetMaximum())
    hy_layer4_fast.Scale(1./hy_layer4_fast.GetMaximum())


    hxlay0prim.Scale(1./hxlay0prim.GetMaximum())
    hylay0prim.Scale(1./hylay0prim.GetMaximum())
    hxlay1prim.Scale(1./hxlay1prim.GetMaximum())
    hylay1prim.Scale(1./hylay1prim.GetMaximum())
    hxlay2prim.Scale(1./hxlay2prim.GetMaximum())
    hylay2prim.Scale(1./hylay2prim.GetMaximum())
    hxlay3prim.Scale(1./hxlay3prim.GetMaximum())
    hylay3prim.Scale(1./hylay3prim.GetMaximum())
    hxlay4prim.Scale(1./hxlay4prim.GetMaximum())
    hylay4prim.Scale(1./hylay4prim.GetMaximum())

    ROOT.gStyle.SetOptStat(0)
    cv2 = ROOT.TCanvas("cv2", "Comparison of Hits per Layer", 2000, 1400)
    cv2.Divide(5, 2)
    cv2.cd(1)
    hxlay0prim.Draw("HIST")
    hx_layer0.Draw("HIST SAME")    
    hx_layer0_fast.Draw("HIST SAME")    
    cv2.cd(2)
    hxlay1prim.Draw("HIST")
    hx_layer1.Draw("HIST SAME")  
    hx_layer1_fast.Draw("HIST SAME")    
    cv2.cd(3)
    hxlay2prim.Draw("HIST")
    hx_layer2.Draw("HIST SAME")    
    hx_layer2_fast.Draw("HIST SAME")    
    cv2.cd(4)
    hxlay3prim.Draw("HIST")
    hx_layer3.Draw("HIST SAME")    
    hx_layer3_fast.Draw("HIST SAME")    
    cv2.cd(5)
    hylay4prim.Draw("HIST")
    hy_layer4.Draw("HIST SAME") 
    hy_layer4_fast.Draw("HIST SAME") 
    cv2.cd(6)
    hylay0prim.Draw("HIST")
    hy_layer0.Draw("HIST SAME")    
    hy_layer0_fast.Draw("HIST SAME")    
    cv2.cd(7)
    hylay1prim.Draw("HIST")
    hy_layer1.Draw("HIST SAME")    
    hy_layer1_fast.Draw("HIST SAME")    
    cv2.cd(8)
    hylay2prim.Draw("HIST")
    hy_layer2.Draw("HIST SAME")    
    hy_layer2_fast.Draw("HIST SAME")    
    cv2.cd(9)
    hylay3prim.Draw("HIST")
    hy_layer3.Draw("HIST SAME")    
    hy_layer3_fast.Draw("HIST SAME")    
    cv2.cd(10)
    hylay4prim.Draw("HIST")
    hy_layer4.Draw("HIST SAME")  
    hy_layer4_fast.Draw("HIST SAME")      
    cv2.Update()
    legend = ROOT.TLegend(0.1, 0.7, 0.5, 0.9)
    legend.AddEntry(hxlay0prim, "Geant4", "l")
    legend.AddEntry(hx_layer0, "FATRAS", "l")
    legend.AddEntry(hx_layer0_fast, "FAST", "l")
    cv2.cd(1)
    legend.Draw("same")
    cv2.SaveAs("comparison_hits_per_layer.png")

    hx_layer0.Scale(1./hx_layer0.GetEntries())
    hy_layer0.Scale(1./hy_layer0.GetEntries())
    hx_layer1.Scale(1./hx_layer1.GetEntries())
    hy_layer1.Scale(1./hy_layer1.GetEntries())
    hx_layer2.Scale(1./hx_layer2.GetEntries())
    hy_layer2.Scale(1./hy_layer2.GetEntries())
    hx_layer3.Scale(1./hx_layer3.GetEntries())
    hy_layer3.Scale(1./hy_layer3.GetEntries())
    hx_layer4.Scale(1./hx_layer4.GetEntries())
    hy_layer4.Scale(1./hy_layer4.GetEntries())

    hx_layer0_fast.Scale(1./hx_layer0_fast.GetEntries())
    hy_layer0_fast.Scale(1./hy_layer0_fast.GetEntries())
    hx_layer1_fast.Scale(1./hx_layer1_fast.GetEntries())
    hy_layer1_fast.Scale(1./hy_layer1_fast.GetEntries())
    hx_layer2_fast.Scale(1./hx_layer2_fast.GetEntries())
    hy_layer2_fast.Scale(1./hy_layer2_fast.GetEntries())
    hx_layer3_fast.Scale(1./hx_layer3_fast.GetEntries())
    hy_layer3_fast.Scale(1./hy_layer3_fast.GetEntries())
    hx_layer4_fast.Scale(1./hx_layer4_fast.GetEntries())
    hy_layer4_fast.Scale(1./hy_layer4_fast.GetEntries())


    hxlay0prim.Scale(1./hxlay0prim.GetEntries())
    hylay0prim.Scale(1./hylay0prim.GetEntries())
    hxlay1prim.Scale(1./hxlay1prim.GetEntries())
    hylay1prim.Scale(1./hylay1prim.GetEntries())
    hxlay2prim.Scale(1./hxlay2prim.GetEntries())
    hylay2prim.Scale(1./hylay2prim.GetEntries())
    hxlay3prim.Scale(1./hxlay3prim.GetEntries())
    hylay3prim.Scale(1./hylay3prim.GetEntries())
    hxlay4prim.Scale(1./hxlay4prim.GetEntries())
    hylay4prim.Scale(1./hylay4prim.GetEntries())

    cv3 = ROOT.TCanvas("cv3", "Comparison of Hits per Layer", 2000, 1400)
    cv3.Divide(5, 2)
    cv3.cd(1)
    hxlay0prim.Draw("HIST")
    hx_layer0.Draw("HIST SAME")    
    hx_layer0_fast.Draw("HIST SAME")    
    cv3.cd(2)
    hxlay1prim.Draw("HIST")
    hx_layer1.Draw("HIST SAME")  
    hx_layer1_fast.Draw("HIST SAME")    
    cv3.cd(3)
    hxlay2prim.Draw("HIST")
    hx_layer2.Draw("HIST SAME")    
    hx_layer2_fast.Draw("HIST SAME")    
    cv3.cd(4)
    hxlay3prim.Draw("HIST")
    hx_layer3.Draw("HIST SAME")    
    hx_layer3_fast.Draw("HIST SAME")    
    cv3.cd(5)
    hylay4prim.Draw("HIST")
    hy_layer4.Draw("HIST SAME") 
    hy_layer4_fast.Draw("HIST SAME") 
    cv3.cd(6)
    hylay0prim.Draw("HIST")
    hy_layer0.Draw("HIST SAME")    
    hy_layer0_fast.Draw("HIST SAME")    
    cv3.cd(7)
    hylay1prim.Draw("HIST")
    hy_layer1.Draw("HIST SAME")    
    hy_layer1_fast.Draw("HIST SAME")    
    cv3.cd(8)
    hylay2prim.Draw("HIST")
    hy_layer2.Draw("HIST SAME")    
    hy_layer2_fast.Draw("HIST SAME")    
    cv3.cd(9)
    hylay3prim.Draw("HIST")
    hy_layer3.Draw("HIST SAME")    
    hy_layer3_fast.Draw("HIST SAME")    
    cv3.cd(10)
    hylay4prim.Draw("HIST")
    hy_layer4.Draw("HIST SAME")  
    hy_layer4_fast.Draw("HIST SAME")      
    cv3.Update()
    legend = ROOT.TLegend(0.1, 0.7, 0.5, 0.9)
    legend.AddEntry(hxlay0prim, "Geant4", "l")
    legend.AddEntry(hx_layer0, "FATRAS", "l")
    legend.AddEntry(hx_layer0_fast, "FAST", "l")
    cv3.cd(1)
    legend.Draw("same")
    cv3.SaveAs("comparison_hits_per_layer_entries.png")